name: octave_tunes_player_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#D9ED92"
  image: assets/images/Splash_Screen.png
  android_12:
    image: assets/images/Splash_Screen.png
    color: "#D9ED92"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/


